baseurl = "https://www.naimcinar.com"
title = "naimcinar"
theme = "hugo-coder"
googleAnalytics = "UA-189160203-1"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "www-naimcinar-com"

enableemoji = true

[params]
    author = "Naim Cinar"
    info = "(Ph.D.) Advertising and Public Relations"
    description = "Naim Cinar's academic website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar-naim.png"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "naimcinar.com" 

    dateformat = "January 2, 2006"

    hidecredits = false
    hidecopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = ""

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    math = true
    custom_css = ["css/custom.css"]

[taxonomies]
  series = "series"

# Social links
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 1
    url = "https://www.instagram.com/naimcinar/"
[[params.social]]
    name = "AnadoluUniversity"
    icon = "fa fa-university fa-2x"
    weight = 2
    url = "https://akademik.anadolu.edu.tr/naimcinar"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/naim-cinar-39116730/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 4
    url = "https://github.com/nakiamo"
[[params.social]]
    name = "Orcid"
    icon = "fab fa-orcid fa-2x"
    weight = 5
    url = "https://orcid.org/0000-0002-1824-4076"


# Menu links
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "Photography"
    weight = 3
    url  = "https://naimcinar.myportfolio.com/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Teaching"
    weight = 4
    url = "/teaching/"
[[menu.main]]
    name = "Publications"
    weight = 5
    url = "/publication/"
[[menu.main]]
    name = "Contact Me"
    weight = 6
    url = "/contact/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5